version: '3.7'

services:
  app:
    container_name: ml_app
    build: .
    env_file:
      - .env
    command: bash -c "
      uvicorn app.main:app
      --host 0.0.0.0 --port 8080
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload --log-level debug
      "
    volumes:
      - .:/home/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres


  postgres:
    image: postgres:16
    container_name: ml_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=ml_password
      - POSTGRES_USER=ml_user
      - POSTGRES_DB=ml_db
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
    name: postgres_data
    
#networks:
#  default: 
#    name: hello_ml